### ISSUE TITLE
Programming is misspelled in a folder

### ISSUE THREAD

**Issue by mobluse** [yelvlab/BPI-BIT#2]
Programming is misspelled in a folder:
https://github.com/yelvlab/BPI-BIT/tree/master/programing

**Comment by yelvlab** [comment]
Oh,Thank you,I have already corrected

**Comment by mobluse** [comment]
The link at programming存放BPI:bit板各种烧录方式的介绍 is wrong now, because it goes to the old name.

**Comment by yelvlab** [comment]
I have made changes and can be closed
